import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Canvas from "../components/Canvas/CanvasHome";
import Header from "../components/Header/Header";
import connectDB from "../database/connectDB";

export async function getServerSideProps(context: GetStaticPropsContext) {
  let res = await fetch("http://localhost:3000/api/scores", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  let allPosts = await res.json();
  return {
    props: { allPosts },
  };
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pau-Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
