import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Canvas from "../components/Canvas/CanvasHome";
import Header from "../components/Header/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pau-Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
